ecommerce_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: warehouse
      user: warehouse
      password: warehouse
      port: 5432
      dbname: ecommerce_dw
      schema: staging
      threads: 4
      keepalives_idle: 0
      search_path: "warehouse,staging,raw"
    
    prod:
      type: postgres
      host: "{{ env_var('WAREHOUSE_HOST') }}"
      user: "{{ env_var('WAREHOUSE_USER') }}"
      password: "{{ env_var('WAREHOUSE_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('WAREHOUSE_DB') }}"
      schema: staging
      threads: 8
      keepalives_idle: 0
      search_path: "warehouse,staging,raw"