version: 2

models:
  - name: dim_customers
    description: Customer dimension with SCD Type 2 implementation
    columns:
      - name: customer_key
        description: Surrogate key for customer dimension
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Business key for customer
        tests:
          - unique
          - not_null
      - name: email
        description: Customer email address
        tests:
          - unique
          - not_null
      - name: customer_lifetime_value
        description: Calculated customer lifetime value
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 50000
      - name: total_orders
        description: Total number of completed orders
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: is_current
        description: Current record indicator for SCD Type 2
        tests:
          - not_null
          - accepted_values:
              values: [true, false]

  - name: dim_products
    description: Product dimension table
    columns:
      - name: product_key
        description: Surrogate key for product dimension
        tests:
          - unique
          - not_null
      - name: product_id
        description: Business key for product
        tests:
          - unique
          - not_null
      - name: price
        description: Product selling price
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 10000
      - name: cost
        description: Product cost
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 5000
      - name: margin_percent
        description: Profit margin percentage
        tests:
          - dbt_utils.accepted_range:
              min_value: -100
              max_value: 100

  - name: dim_date
    description: Date dimension for time-based analysis
    columns:
      - name: date_key
        description: Surrogate key in YYYYMMDD format
        tests:
          - unique
          - not_null
      - name: date_actual
        description: Actual date value
        tests:
          - unique
          - not_null
      - name: day_of_week
        description: Day of week (0=Sunday, 6=Saturday)
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 6
      - name: month_actual
        description: Month number
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 12

  - name: fact_orders
    description: Orders fact table
    columns:
      - name: order_key
        description: Surrogate key for orders fact
        tests:
          - unique
          - not_null
      - name: order_id
        description: Business key for order
        tests:
          - unique
          - not_null
      - name: customer_key
        description: Foreign key to customer dimension
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_key
      - name: date_key
        description: Foreign key to date dimension
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
      - name: total_amount
        description: Total order amount
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 50000
      - name: tax_rate_percent
        description: Tax rate as percentage
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 50

  - name: fact_order_items
    description: Order items fact table
    columns:
      - name: order_item_key
        description: Surrogate key for order items
        tests:
          - unique
          - not_null
      - name: order_key
        description: Foreign key to orders fact
        tests:
          - not_null
          - relationships:
              to: ref('fact_orders')
              field: order_key
      - name: product_key
        description: Foreign key to product dimension
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_key
      - name: quantity
        description: Quantity ordered
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 100
      - name: line_total
        description: Line item total
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
    tests:
      - name: test_customer_orders_consistency
        description: Ensure customer order counts match between dimensions and facts
      - name: test_revenue_reconciliation
        description: Ensure revenue totals match between order and order item facts