version: 2

models:
  - name: dim_customers
    description: Customer dimension with SCD Type 2 implementation
    columns:
      - name: customer_key
        description: Surrogate key for customer dimension
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Business key for customer
        tests:
          - unique
          - not_null

  - name: dim_date
    description: Date dimension for time-based analysis
    columns:
      - name: date_key
        description: Surrogate key in YYYYMMDD format
        tests:
          - unique
          - not_null
      - name: date_actual
        description: Actual date value
        tests:
          - unique
          - not_null

  - name: fact_orders
    description: Orders fact table
    columns:
      - name: order_key
        description: Surrogate key for orders fact
        tests:
          - unique
          - not_null
      - name: order_id
        description: Business key for order
        tests:
          - unique
          - not_null